version: '3.8'

services:
  easydoh:
    image: ghcr.io/isa0-gh/easydoh:latest
    container_name: easydoh
    restart: unless-stopped
    ports:
      - "53:53/udp"
    volumes:
      - /etc/easydoh:/etc/easydoh
