version: '3.8'

services:
  resolv:
    image: ghcr.io/isa0-gh/resolv:latest
    container_name: resolv
    restart: unless-stopped
    ports:
      - "53:53/udp"
    volumes:
      - ./config.toml:/app/config.toml
